from __future__ import annotations

from typing import AsyncIterator, Protocol

from pinky_control_center.models import AdapterEvent, CameraFrame, CommandAcceptance, CommandRequest


class RobotAdapter(Protocol):
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def execute(self, command: CommandRequest) -> CommandAcceptance: ...
    def events(self) -> AsyncIterator[AdapterEvent]: ...
    def frames(self, robot_id: str) -> AsyncIterator[CameraFrame]: ...
