import { act, cleanup, render, screen } from '@testing-library/react'
import '@testing-library/jest-dom/vitest'
import { beforeEach, expect, test, vi } from 'vitest'
import CameraGrid from './CameraGrid'

class FakeSocket { static all: FakeSocket[] = []; onopen = () => {}; onmessage = (_: MessageEvent) => {}; onclose = (_: CloseEvent) => {}; onerror = () => {}; binaryType = ''; close = vi.fn(); constructor(public url: string) { FakeSocket.all.push(this) } }
beforeEach(() => { cleanup(); vi.useFakeTimers(); FakeSocket.all = []; vi.stubGlobal('WebSocket', FakeSocket); vi.stubGlobal('URL', { createObjectURL: vi.fn(() => 'blob:frame'), revokeObjectURL: vi.fn() }); vi.stubGlobal('Blob', class { constructor(public parts: unknown[]) {} }) })
function validFrame(frameId = 'frame') { const metadata = new TextEncoder().encode(JSON.stringify({ frame_id: frameId, captured_at: null, received_at: 'now', width: 2, height: 1 })); const bytes = new Uint8Array(4 + metadata.length + 4); new DataView(bytes.buffer).setUint32(0, metadata.length); bytes.set(metadata, 4); bytes.set([255, 216, 255, 217], 4 + metadata.length); return bytes.buffer }
test('renders master before slave and hides only stalled tile after five seconds', () => { render(<CameraGrid robots={[{ robot_id: 'robot_2', name: 'Slave', role: 'SLAVE', connection: 'ONLINE' }, { robot_id: 'robot_1', name: 'Master', role: 'MASTER', connection: 'ONLINE' }]} />); expect(screen.getAllByRole('article').map(node => node.textContent)).toEqual(expect.arrayContaining([expect.stringContaining('Master'), expect.stringContaining('Slave')])); expect(screen.getAllByRole('article')[0]).toHaveTextContent('Master'); const frame = new ArrayBuffer(0); act(() => FakeSocket.all[0].onmessage(new MessageEvent('message', { data: frame }))); act(() => vi.advanceTimersByTime(5000)); expect(screen.getAllByRole('article')[0]).toHaveTextContent('영상 없음') })
test('supports quality selection and marks session expiry', () => { render(<CameraGrid robots={[{ robot_id: 'robot_1', name: 'Master', role: 'MASTER', connection: 'ONLINE' }]} />); expect(screen.getByLabelText('화질')).toBeInTheDocument(); act(() => FakeSocket.all[0].onclose(new CloseEvent('close', { code: 4401 }))); expect(screen.getByText('세션 만료')).toBeInTheDocument() })
test('initializes camera tiles from the persisted quality', () => { render(<CameraGrid initialQuality="high" robots={[{ robot_id: 'robot_1', name: 'Master', role: 'MASTER', connection: 'ONLINE' }]} />); expect(screen.getByLabelText('화질')).toHaveValue('high'); expect(FakeSocket.all[0].url).toContain('quality=high') })
test('renders only JPEG bytes and reports measured FPS', () => { render(<CameraGrid robots={[{ robot_id: 'robot_1', name: 'Master', role: 'MASTER', connection: 'ONLINE' }]} />); act(() => FakeSocket.all[0].onmessage(new MessageEvent('message', { data: validFrame('one') }))); vi.setSystemTime(Date.now() + 100); act(() => FakeSocket.all[0].onmessage(new MessageEvent('message', { data: validFrame('two') }))); const blob = vi.mocked(URL.createObjectURL).mock.calls[0][0] as unknown as { parts: unknown[] }; expect(Array.from(blob.parts[0] as Uint8Array).slice(0, 2)).toEqual([255, 216]); expect(screen.getByText(/FPS 2/)).toBeInTheDocument() })
test('does not reorder the caller robot array', () => { const robots = [{ robot_id: 'robot_2', name: 'Slave', role: 'SLAVE', connection: 'ONLINE' }, { robot_id: 'robot_1', name: 'Master', role: 'MASTER', connection: 'ONLINE' }]; render(<CameraGrid robots={robots} />); expect(robots.map(robot => robot.robot_id)).toEqual(['robot_2', 'robot_1']) })
