import { expect, test } from 'vitest'
import { canvasToWorld, centerViewOnWorld, isFreeOccupancyCell, staleAgeLabel, worldToCanvas } from './transforms'
const map = { width: 200, height: 100, resolution: .1, origin: { x: 2, y: -3, yaw: .37 } }
const view = { scale: 1.8, offsetX: 23, offsetY: -9 }
test('world/canvas roundtrip preserves translated rotated map coordinates', () => { for (const point of [{ x: 2.1, y: -2.9 }, { x: 5, y: 1 }, { x: -3, y: 4 }]) { const canvas = worldToCanvas(point, map, view); const result = canvasToWorld(canvas, map, view); expect(Math.hypot(result.x - point.x, result.y - point.y)).toBeLessThanOrEqual(1e-6) } })
test('zoom and pan are reversible for goal preview coordinates', () => { const goal = { x: 4.2, y: 1.8 }; const zoomed = worldToCanvas(goal, map, { scale: 2.5, offsetX: -31, offsetY: 14 }); expect(canvasToWorld(zoomed, map, { scale: 2.5, offsetX: -31, offsetY: 14 })).toEqual(expect.objectContaining({ x: expect.closeTo(goal.x, 6), y: expect.closeTo(goal.y, 6) })) })
test('follow view centers the selected robot', () => { const point = { x: 4.2, y: 1.8 }; const view = centerViewOnWorld(point, map, 1.5); expect(worldToCanvas(point, map, view)).toEqual({ x: map.width / 2, y: map.height / 2 }) })
test('only free occupancy cells accept a goal preview', () => { const cells = new Uint8ClampedArray(200 * 100).fill(254); const free = { x: 2.1, y: -2.9 }; const pixel = worldToCanvas(free, map, { scale: 1, offsetX: 0, offsetY: 0 }); cells[Math.floor(pixel.y) * map.width + Math.floor(pixel.x)] = 0; expect(isFreeOccupancyCell(free, map, cells)).toBe(false); cells[Math.floor(pixel.y) * map.width + Math.floor(pixel.x)] = 205; expect(isFreeOccupancyCell(free, map, cells)).toBe(false); cells[Math.floor(pixel.y) * map.width + Math.floor(pixel.x)] = 254; expect(isFreeOccupancyCell(free, map, cells)).toBe(true) })
test('a world cell resolves to its top-down PNG row for occupancy', () => { const mock = { width: 20, height: 20, resolution: .1, origin: { x: 0, y: 0, yaw: 0 } }; const cells = new Uint8ClampedArray(400).fill(254); const worldCell = { x: .85, y: 1.45 }; const pixel = worldToCanvas(worldCell, mock, { scale: 1, offsetX: 0, offsetY: 0 }); expect({ x: Math.floor(pixel.x), y: Math.floor(pixel.y) }).toEqual({ x: 8, y: 5 }); cells[5 * 20 + 8] = 0; expect(isFreeOccupancyCell(worldCell, mock, cells)).toBe(false) })
test('stale age is based on the last received timestamp', () => expect(staleAgeLabel('2026-01-01T00:00:00Z', Date.parse('2026-01-01T00:00:07Z'))).toBe('7초 전'))
